# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
# IP: The module: 'design_1_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
# IP: The module: 'design_1_proc_sys_reset_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Git/Final-Project-ECE520/Hardware/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
